global:
  scrape_interval: 15s  # 采集数据的时间间隔

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']

  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]

  - job_name: 'test_service'
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
    metrics_path: 'index.php/api/metrics'